spring:
  datasource:
    url: jdbc:postgresql://db:5432/CarStore
    username: postgres
    password: 301600
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090
security:
  jwt:
    secret: cXdlZzEyM2cxNDJndTojSUgxcGlIUGloJ3AndTEzZ3QncDEzcGhwJ2YzaCdwaWZoRUpKUUxFSERM
    access: 3600000
    refresh: 2592000000